name: school

mysql:
  name:shcool
  host:127.0.0.1
  port:3306
  username:root
  password:123456
  charset:utf8mb4
  max-idle-connections:10
  max-open-connections:2
  log-mode:true
redis:
  host:127.0.0.1
  port:6379
  password:
  db:0
gin:
  mode:debug #release,debug
  address:8000